theme: jekyll-theme-hacker
title: Half the world away
description: Blog on maths, computer science and many more
likedin_url: https://www.linkedin.com/in/alexandra-albu-978b98151/
author: Alexandra Albu
github:
  git_url: https://github.com/alexandraalbu
plugins:
  - jemoji
