theme: jekyll-theme-hacker
title: Sampled bits
description: "In theory there is no difference between theory and practice; in practice there is"
likedin_url: https://www.linkedin.com/in/alexandra-albu-978b98151/
author: Alexandra Albu
github:
  git_url: https://github.com/alexandraalbu
plugins:
  - jemoji
